server:
    context-path: /resource-server-jwt
spring:
    datasource:
        password: password
        testWhileIdle: true
        url: jdbc:mysql://127.0.0.1:3306/wallet?useUnicode=true&serverTimezone=UTC
        username: root
        validationQuery: SELECT 1
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        show-sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8083/auth/realms/baeldung
                    jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
